# Set a plain language title for the site.
title: Piano Playground with Miss Sophia Levy

# Write a short description for the site. This is used for "meta description."
description: Achieve freedom in piano playing and develop a lifelong passion in your musical journey and become creative and musical music makers

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally.
github: [metadata]